services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root@db:3306/symfony
    depends_on:
      - db
    networks:
      - symfony

  db:
    image: mysql:8.1
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:3-management
    container_name: symfony_rabbitmq
    ports:
      - "5672:5672"    # Para el protocolo AMQP
      - "15672:15672"  # Para la web de administración
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - symfony

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_worker
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root@db:3306/symfony
    depends_on:
      - db
      - rabbitmq
      - app
    command: php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=128M --no-interaction
    restart: always
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
