services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app/src:/var/www/html/src
      - ./app/bin:/var/www/html/bin
      - ./app/config:/var/www/html/config
      - ./app/public:/var/www/html/public
      - ./app/migrations:/var/www/html/migrations
      - ./app/features:/var/www/html/features
      - var_data:/var/www/html/var # cache y logs SOLO en el contenedor
      # Si quieres montar tests para correr pruebas, puedes agregar:
      - ./app/tests:/var/www/html/tests
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://symfony:symfony@db:5432/symfony?serverVersion=16&charset=utf8
    depends_on:
      - db
    networks:
      - symfony

  worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: symfony_worker
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://symfony:symfony@db:5432/symfony?serverVersion=16&charset=utf8
    depends_on:
      - db
      - rabbitmq
      - app
    command: php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=128M --no-interaction
    restart: always
    networks:
      - symfony

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - symfony

  db:
    image: postgres:16
    container_name: symfony_db
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: symfony_phpmyadmin
#    restart: always
#    ports:
#      - "8081:80"
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: root
#      PMA_ARBITRARY: 1
#    depends_on:
#      - db
#    networks:
#      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:3-management
    container_name: symfony_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - symfony

volumes:
  db_data:
  var_data:
  pgadmin_data:

networks:
  symfony:
    driver: bridge
