request_information_controllers:
    resource:
        path: ../src/RequestInformation/Infrastructure/Controller/
        namespace: App\RequestInformation\Infrastructure\Controller
    type: attribute
quotation_controllers:
    resource:
        path: ../src/Quotation/Infrastructure/Controller/
        namespace: App\Quotation\Infrastructure\Controller
    type: attribute
common_controllers:
    resource:
        path: ../src/Common/Infrastructure/Controller/
        namespace: App\Common\Infrastructure\Controller
    type: attribute
activation_controllers:
    resource:
        path: ../src/Activation/Infrastructure/Controller/
        namespace: App\Activation\Infrastructure\Controller
    type: attribute
assignee_controllers:
    resource:
        path: ../src/Assignee/Infrastructure/Controller/
        namespace: App\Assignee\Infrastructure\Controller
    type: attribute
landing_page_controllers:
    resource:
        path: ../src/LandingPage/Infrastructure/Controller/
        namespace: App\LandingPage\Infrastructure\Controller
    type: attribute
potential_customer_controllers:
    resource:
        path: ../src/PotentialCustomer/Infrastructure/Controller/
        namespace: App\PotentialCustomer\Infrastructure\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
