<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250808195905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE potential_customer (id UUID NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, phone VARCHAR(32) DEFAULT NULL, city VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE potential_customer_email (id UUID NOT NULL, value VARCHAR(255) NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, potential_customer_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DCBDAA8D96798203 ON potential_customer_email (potential_customer_id)');
        $this->addSql('CREATE TABLE quotation (id UUID NOT NULL, details JSON NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, request_information_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_474A8DB975A68C6C ON quotation (request_information_id)');
        $this->addSql('CREATE TABLE request_information (id UUID NOT NULL, organization_id VARCHAR(36) NOT NULL, program_interest_id VARCHAR(36) NOT NULL, lead_origin_id VARCHAR(36) NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(32) NOT NULL, city VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_user_updated JSON DEFAULT NULL, status_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_285BBD66BF700BD ON request_information (status_id)');
        $this->addSql('CREATE INDEX idx_program_interest_id ON request_information (program_interest_id)');
        $this->addSql('CREATE INDEX idx_lead_origin_id ON request_information (lead_origin_id)');
        $this->addSql('CREATE INDEX idx_organization_id ON request_information (organization_id)');
        $this->addSql('CREATE TABLE request_information_status (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, organization_id VARCHAR(36) NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E922A03F77153098 ON request_information_status (code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_code_organization ON request_information_status (code, organization_id)');
        $this->addSql('CREATE TABLE request_note (id UUID NOT NULL, text VARCHAR(512) NOT NULL, created_by VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, request_information_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B01ADDEE75A68C6C ON request_note (request_information_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE potential_customer_email ADD CONSTRAINT FK_DCBDAA8D96798203 FOREIGN KEY (potential_customer_id) REFERENCES potential_customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quotation ADD CONSTRAINT FK_474A8DB975A68C6C FOREIGN KEY (request_information_id) REFERENCES request_information (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_information ADD CONSTRAINT FK_285BBD66BF700BD FOREIGN KEY (status_id) REFERENCES request_information_status (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_note ADD CONSTRAINT FK_B01ADDEE75A68C6C FOREIGN KEY (request_information_id) REFERENCES request_information (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE potential_customer_email DROP CONSTRAINT FK_DCBDAA8D96798203');
        $this->addSql('ALTER TABLE quotation DROP CONSTRAINT FK_474A8DB975A68C6C');
        $this->addSql('ALTER TABLE request_information DROP CONSTRAINT FK_285BBD66BF700BD');
        $this->addSql('ALTER TABLE request_note DROP CONSTRAINT FK_B01ADDEE75A68C6C');
        $this->addSql('DROP TABLE potential_customer');
        $this->addSql('DROP TABLE potential_customer_email');
        $this->addSql('DROP TABLE quotation');
        $this->addSql('DROP TABLE request_information');
        $this->addSql('DROP TABLE request_information_status');
        $this->addSql('DROP TABLE request_note');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
