doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            RequestInformation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/RequestInformation/Infrastructure/Persistence'
                prefix: 'App\RequestInformation\Infrastructure\Persistence'
                alias: RequestInformationPersistence
            PotentialCustomer:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/PotentialCustomer/Infrastructure/Persistence'
                prefix: 'App\PotentialCustomer\Infrastructure\Persistence'
                alias: PotentialCustomerPersistence
            Quotation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Quotation/Infrastructure/Persistence'
                prefix: 'App\Quotation\Infrastructure\Persistence'
                alias: QuotationPersistence
            Assignee:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Assignee/Infrastructure/Persistence'
                prefix: 'App\Assignee\Infrastructure\Persistence'
                alias: AssigneePersistence
            Activation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Activation/Infrastructure/Persistence'
                prefix: 'App\Activation\Infrastructure\Persistence'
                alias: ActivationPersistence
            LandingPage:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/LandingPage/Infrastructure/Persistence'
                prefix: 'App\LandingPage\Infrastructure\Persistence'
                alias: LandingPagePersistence
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
