nelmio_api_doc:
    documentation:
        info:
            title: 'Potential Customer management API'
            description: |
                API RESTful para gesti칩n de solicitudes de informaci칩n, posibles clientes, ventas y seguimiento.
                Documenta todos los servicios bajo `/api`.
            version: '1.0.0'
        servers:
            - url: 'https://crm.pitahayasoft.com'
              description: 'Customer Relationship Management'
            # Agrega m치s servers si tienes ambientes de staging/prod:
            # - url: 'https://api.midominio.com'
            #   description: 'Producci칩n'
        contact:
            name: 'Equipo PitahayaSoft'
            email: 'soporte@pitahayasoft.com'
            url: 'https://crm.pitahayasoft.com'
        license:
            name: 'MIT'
            url: 'https://opensource.org/licenses/MIT'
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
    models:
        use_jms: false
